### ISSUE TITLE
CARTOGRAPHER_TOUCH disapear

### ISSUE THREAD

**Issue by hougoul** [Cartographer3D/cartographer-klipper#177]
After upgrade of Klipper and Cartographer to the last version.
After applied the probe register fix
I cannot do any command CARTOGRAPHER_TOUCH anymore.

**Comment by Jomik** [comment]
Please help us help you.
How are we supposed to do anything when you provide us absolutely no information.
`CARTOGRAPHER_TOUCH` works fine here.
We will need your `klippy.log`, preferably roll it before you upload it so that it is small.
Issues like this are easier to resolve via [Discord](https://discord.com/channels/1165274913624572014/1229798364514750596).

**Comment by hougoul** [comment]
Sorry,
I will try to give it as soon as possible. But I think it's because scanner.py is not in my klipper/klippy/extra folder.

**Comment by krautech** [comment]
Ahh you need to do

`cd ~/cartographer-klipper
./install.sh`

**Comment by liangw1024** [comment]
I ran CARTOGRAPHER-TOUCH, and after 10/10, it prompted that the nozzle had not reached the extrusion temperature
My touch spray temperature is 145 ° C

**Comment by Jomik** [comment]
@liangw1024 Please create your own issue, as it is not the same problem. Or preferably, open a thread in our Discord.
https://discord.com/invite/EFSwpureHz
https://discord.com/channels/1165274913624572014/1229798364514750596
